version: "3"
services: 
  hooks:
    build: ./
    image: dalongrong/webhook-docker-client
    command: ["-verbose", "-hooks=/etc/webhook/hooks.json","-hotreload"]
    tty: true
    volumes:
    - "./conf/hooks.json:/etc/webhook/hooks.json"
    - "./app.sh:/app.sh"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./result:/opt/result"
    - "./gitcode:/opt/gitcode"
    - "./gitcode/.git:/opt/gitcode/.git"
    ports:
    - "9090:9000"
    privileged: true